# Generated by Django 5.1.4 on 2025-01-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Antibody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_db", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("sequence_VH", models.TextField()),
                ("sequence_VL", models.TextField()),
                ("sequence_CH2", models.TextField()),
                ("sequence_CH3", models.TextField()),
                ("reference", models.TextField()),
                ("doi", models.URLField()),
                ("properties", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
