# Generated by Django 5.1.4 on 2025-01-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_antibody_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="id_db",
            field=models.TextField(blank=True, null=True),
        ),
    ]
