# Generated by Django 5.1.4 on 2025-01-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_antibody_id_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="property_keys",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
