# Generated by Django 5.1.4 on 2025-01-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_antibody_property_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antibody",
            name="property_keys",
            field=models.TextField(blank=True, null=True),
        ),
    ]
