# Generated by Django 5.1.4 on 2025-01-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_antibody_property_keys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antibody",
            name="sequence_CH2",
        ),
        migrations.RemoveField(
            model_name="antibody",
            name="sequence_CH3",
        ),
        migrations.RemoveField(
            model_name="antibody",
            name="sequence_VH",
        ),
        migrations.RemoveField(
            model_name="antibody",
            name="sequence_VL",
        ),
        migrations.AddField(
            model_name="antibody",
            name="sequence",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
