# Generated by Django 5.1.4 on 2025-05-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_delete_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="paper",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
