# Generated by Django 5.1.4 on 2025-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_antibody_paper"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="format",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antibody",
            name="orgnism",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antibody",
            name="other_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
