# Generated by Django 5.1.4 on 2025-05-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_antibody_format_antibody_orgnism_antibody_other_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="antibody",
            old_name="orgnism",
            new_name="organism",
        ),
    ]
