# Generated by Django 5.1.4 on 2025-05-30 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_orgnism_antibody_organism"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antibody",
            name="properties",
        ),
        migrations.RemoveField(
            model_name="antibody",
            name="property_keys",
        ),
        migrations.CreateModel(
            name="AntibodyProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("assay", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_list",
                        to="blog.antibody",
                    ),
                ),
            ],
        ),
    ]
